osx_image: xcode8.3
language: swift
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- xcodebuild clean build test -workspace Example/ALSlidingNavigationBar.xcworkspace -scheme ALSlidingNavigationBar-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- pod lib lint