osx_image: xcode8.3
language: swift
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- xcodebuild test -workspace Example/ALSlidingNavigationBar.xcworkspace -scheme ALSlidingNavigationBar-Example -destination 'platform=iOS Simulator,name=iPhone7 Plus,OS=10.3.1' ONLY_ACTIVE_ARCH=NO
- pod lib lint